version: '2'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    group_add:
      - 999
    environment:
      - JAVA_OPTS="-Xmx8192m"
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
    volumes:
      - /home/ubuntu/CaddyJenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/go:/usr/local/go
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7

  caddy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - "jenkins"
    environment:
      - CADDYPATH=/etc/caddycerts
    volumes:
      - /home/ubuntu/CaddyJenkins/Caddyfile:/etc/Caddyfile
      - /home/ubuntu/CaddyJenkins/caddy:/etc/caddycerts
