version: '2'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    group_add:
      - ${DOCKERGID}
    environment:
      - JAVA_OPTS="-Xmx4096m"
      - JENKINS_HOME=${PWD}/jenkins_home
    volumes:
      - ${PWD}/jenkins_home:${PWD}/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  caddy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - "jenkins"
    environment:
      - CADDYPATH=/etc/caddycerts
    volumes:
      - /home/ubuntu/CaddyJenkins/Caddyfile:/etc/Caddyfile
      - /home/ubuntu/CaddyJenkins/caddy:/etc/caddycerts
